// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CPIInflation
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("yearMonth")]
        public string YearMonth { get; set; }

        [JsonProperty("year")]
        public long Year { get; set; }

        [JsonProperty("month")]
        public long Month { get; set; }

        [JsonProperty("categories")]
        public Categories Categories { get; set; }
    }

    public partial class Categories
    {
        [JsonProperty("all")]
        public All All { get; set; }

        [JsonProperty("food")]
        public All Food { get; set; }

        [JsonProperty("housing")]
        public All Housing { get; set; }

        [JsonProperty("transportation")]
        public All Transportation { get; set; }

        [JsonProperty("medical")]
        public All Medical { get; set; }

        [JsonProperty("gasoline")]
        public All Gasoline { get; set; }

        [JsonProperty("electricity")]
        public All Electricity { get; set; }
    }

    public partial class All
    {
        [JsonProperty("index")]
        public double Index { get; set; }

        [JsonProperty("yearOverYearChange")]
        public double YearOverYearChange { get; set; }
    }
}
